### ISSUE TITLE
Upgrading today from `"@sveltejs/kit": "1.30.0"` to `"@sveltejs/kit": "2.0.0"` I'm getting a warning

### ISSUE THREAD

**Issue by frederikhors** [fedorovvvv/svelte-floating-ui#11]
Upgrading today from `"@sveltejs/kit": "1.30.0"` to `"@sveltejs/kit": "2.0.0"` I'm getting this warning:

```
WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-select@5.8.1
svelte-floating-ui@1.2.8

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.
```

Can we please fix this?

**Comment by fedorovvvv** [comment]
Hi ✨
I fixed this 2 weeks ago in 1.5.8 version╰(*°▽°*)╯

But **svelte-select@5.8.1** uses an outdated version of **svelte-floating-ui@1.2.8**
You can offer them PR with exports)

**Comment by frederikhors** [comment]
Thanks!

> You can offer them PR with exports

What do you mean?

**Comment by fedorovvvv** [comment]
I thought you might suggest changes to package.json for svelte-select, if you have the ability to do so 🌟

**Comment by frederikhors** [comment]
> with exports

Yeah. I don't understand the `with exports` part.

**Comment by fedorovvvv** [comment]
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition
This part 🎅🏻

**Comment by frederikhors** [comment]
Ok. Sorry, I'm very confused today!
