### ISSUE TITLE
Add support for virtual elements

### ISSUE THREAD

**Issue by GiacomoRandazzo** [fedorovvvv/svelte-floating-ui#6]
Hi, 

[Virtual elements](https://floating-ui.com/docs/virtual-elements) are not supported since `ReferenceAction` only accepts `HTMLElement`.

The type signature for `ReferenceAction` is:

```
type ReferenceAction = (node: HTMLElement) => void;
```

For instance, in [svelte-popperjs](https://github.com/bryanmylee/svelte-popperjs) the type signature is:

```
type ReferenceAction = (
	node: Element | VirtualElement | Readable<VirtualElement>
) => {
	destroy?(): void;
};
```

Do you plan to add support for virtual elements?

**Comment by fedorovvvv** [comment]
Hi, yes, this is a wonderful functionality
Thank you for writing about him✨

It is added in the [new release 1.2.7](https://github.com/fedorovvvv/svelte-floating-ui/releases/tag/1.2.7)
A [new block in the documentation](https://github.com/fedorovvvv/svelte-floating-ui#virtual-elements) has also been added to it🎈
