### ISSUE TITLE
Container queries and 'fixed'

### ISSUE THREAD

**Issue by rob-balfre** [fedorovvvv/svelte-floating-ui#7]
Hi @fedorovvvv can `svelte-floating-ui` work inside a  `inline-size` container with a `fixed` element?

It defaults to the root document to calculate the fixed position, is there a way to override this to use the container root instead?

RELP:
https://svelte.dev/repl/897efd599c4748099f65b2f73fc82685?version=4.0.0

Thanks

**Comment by fedorovvvv** [comment]
Hi! I'm not sure exactly, but it's worth looking at the [floating ui documentation](https://floating-ui.com/docs/getting-started).
