### ISSUE TITLE
Infinite onComputed loop with `hide` middleware

### ISSUE THREAD

**Issue by harshmandan** [fedorovvvv/svelte-floating-ui#8]
Hi,

I'm trying to recreate [this](https://floating-ui.com/docs/hide) example in svelte, using `onComputed`, but whenever the reference element goes out of the view the onComputed loop keeps running. 

So my question is if this is normal or expected or if it is a bug?
Also, what is the proper way to use the hide middleware if I'm using it wrong?

Here's the demo REPL: https://svelte.dev/repl/2db64b10d18a4740b81ff707978727bb?version=4.0.4

**Comment by fedorovvvv** [comment]
Hi!✨
Unfortunately, this is how [`autoUpdate` works in the **floating ui**](https://floating-ui.com/docs/autoupdate#autoupdate)
There is nothing we can do about it :(

REPL: https://svelte.dev/repl/2db64b10d18a4740b81ff707978727bb?version=4.0.4

**Comment by harshmandan** [comment]
Oh okay, thanks!
